version: "3.8"

services:
  selenium-hub:
    image: selenium/hub:4.13.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    networks:
      - selenium-grid

  builder:
    build:
      context: ./appium-node
    image: appium-node

# DYNAMIC_SERVICES_PLACEHOLDER

networks:
  selenium-grid:
    driver: bridge
